import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const server=spawn('python3',['-m','http.server','8173','--directory','dist'],{stdio:'ignore'});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
try {
  await expect.poll(async()=>{try{return (await fetch('http://127.0.0.1:8173/')).status;}catch{return 0;}},{timeout:10000}).toBe(200);
  await page.goto('http://127.0.0.1:8173/');
  await expect(page.locator('#browseRows tr').first()).toBeVisible({timeout:120000});
  await expect(page.locator('#browseRows tr')).toHaveCount(100);
  await page.locator('#addFilter').click();
  await page.locator('#fieldSearch').fill('性別');
  await page.locator('[data-field="性別"]').click();
  await page.locator('.value-options label').filter({hasText:'女'}).locator('input').check();
  await expect.poll(async()=>await page.locator('#browseRows td[data-column="性別"]').allTextContents()).toEqual(Array(100).fill('女'));
  await page.locator('#browseNext').click();
  await expect(page.locator('#browsePage')).toContainText('2 ／');
  await page.locator('#browseSql').click();
  await expect(page.locator('#queryWorkspace')).toBeVisible();
  await expect(page.locator('#queryState')).toHaveText('已執行',{timeout:30000});
  await expect(page.locator('.result-pane')).toBeVisible();
  await page.locator('#sqlEditor').fill('SELECT TOP 7 "KEY", "性別" FROM "命盤" ORDER BY "KEY"');
  await page.locator('#sqlEditor').press('F5');
  await expect(page.locator('#gridRows tr')).toHaveCount(7);
  await page.locator('#sqlEditor').fill('SELECT "不存在欄位" FROM "命盤"');
  await page.locator('#sqlEditor').press('F5');
  await expect(page.locator('#queryState')).toHaveText('錯誤');
  await expect(page.locator('#messagesView')).toBeVisible();
  await page.locator('[data-workspace-tab="visualization"]').click();
  await expect(page.locator('.object-explorer')).toBeHidden();
  await expect(page.locator('.viz-stat-link').first()).toBeVisible({timeout:30000});
  await expect(page.locator('.viz-canvas')).toBeVisible();
  await page.locator('.viz-stat-link').first().click();
  await expect(page.locator('.viz-detail')).toContainText('命盤');
  await page.locator('[data-workspace-tab="database"]').click();
  await page.locator('#clearFilters').click();
  await expect(page.locator('#browseRows tr')).toHaveCount(100);
  fs.mkdirSync('test-results',{recursive:true});
  await page.screenshot({path:'test-results/database.png',fullPage:true});
  await page.locator('#themeToggle').click();
  await page.screenshot({path:'test-results/database-dark.png',fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser verified: DuckDB load, filtering, pagination, SQL handoff, F5, errors, calendar, statistics, tab switching.');
} finally {await browser.close();server.kill();}
